# Generated by Django 3.1.2 on 2020-10-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzerias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzerias.pizza')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
