# Generated by Django 3.1.2 on 2020-10-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzerias', '0003_auto_20201020_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='text',
            field=models.TextField(),
        ),
    ]
